### ISSUE TITLE
Modeling support for "Negative Type" statement

### ISSUE THREAD

**Issue by constnick** [mdesalvo/OWLSharp#23]
Hi Marco!
Let there be an individual I0 and a class C0 in the ontology.
What is the optimal way to check, is there an explicit statement that individual I0 does not belong to class C0? 
It must be expressed as belongness to "complementOf C0".
There is the method "CheckHasCompositeClass", but it mixes three different kinds of composite class expressions.

**Comment by mdesalvo** [comment]
Hi constnick, given your individual I0 and your complement class C0, you can use: bool isaCO = myOntology.Data.CheckIsIndividualOf(myOntology.Model, I0, C0);

Regards,
Marco

**Comment by constnick** [comment]
It is checking for — is I0 explicitly belongs to C0 or not.
But I need to check, is I0 _explicitly not belongs_ to C0.
For example in Turtle:
```
test:Man rdf:type owl:NamedIndividual ,
                   test:Human ,
                   [ rdf:type owl:Class ;
                     owl:complementOf test:Japanese
                   ] .
```
It means that `Man` is definitely known as not `Japanese`.
I need to check if there is such a declaration in the ontology.

**Comment by mdesalvo** [comment]
Hi,
although the library is answering your need, I understand that you have a slightly different semantic to prove. This kind of check must be done at SPARQL level, where you have full power of controlling the raw RDF triples of the knowledge in such way:

```csharp
//Get down to RDF/SPARQL level
RDFGraph ontologyGraph = ontology.ToRDFGraph(true);

//Build an ASK query detecting individuals of any complement class, constraining the answer to the "test:Man" individual and "test:Japanese" class to be proven
RDFAskQuery isNotJapaneseQuery = new RDFAskQuery()
    .AddPatternGroup(new RDFPatternGroup()
        .AddPattern(new RDFPattern(new RDFVariable("?IDV"), RDFVocabulary.RDF.TYPE, RDFVocabulary.OWL.NAMED_INDIVIDUAL))
        .AddPattern(new RDFPattern(new RDFVariable("?IDV"), RDFVocabulary.RDF.TYPE, new RDFVariable("?IDVCLS")))
        .AddPattern(new RDFPattern(new RDFVariable("?IDVCLS"), RDFVocabulary.RDF.TYPE, RDFVocabulary.OWL.CLASS))
        .AddPattern(new RDFPattern(new RDFVariable("?IDVCLS"), RDFVocabulary.OWL.COMPLEMENT_OF, new RDFVariable("?NOTIDVCLS")))
        .AddFilter(new RDFSameTermFilter(new RDFVariable("?IDV"), new RDFResource("test:Man")))
        .AddFilter(new RDFSameTermFilter(new RDFVariable("?NOTIDVCLS"), new RDFResource("test:Japanese"))));
RDFAskQueryResult isNotJapaneseQueryResult = isNotJapaneseQuery.ApplyToGraph(ontologyGraph);

Console.Write("test:Man IS NOT test:Japanese? " + isNotJapaneseQueryResult.AskResult);
```

Let me know if this fits yor needs.
Regards,
Marco

**Comment by constnick** [comment]
Yes, certainly I can do what I want with SPARQL, but it would be convenient to have such methods in an ontology object or its component.
By the way:
There are two kinds of "spo" or "spl" statements: positive and negative.
And also there are the same two kinds of "type" statements.
For example, in  Manchester syntax it expressed just with simple "not":
```
Individual: test:Man
    Types: 
        test:Human,
        not (test:Japanese)
```
May be it would be consistent to have symmetrical tools to work with negative "type" statements, just like with negative spo/spl assertions?

**Comment by mdesalvo** [comment]
I didn't know the existence of the "negative type" statement. Maybe a OWL2 syntax which I didn't notice.

So, given an individual "ex:Idv" and a target class "ex:Cls" being the prohibited class, I'll figure how to add modeling support (and comprehensive core validations) for this new construct:
```
ex:Idv rdf:type owl:NamedIndividual, 
                [ rdf:type owl:Class; owl:complementOf ex:Cls ] .
```

Regards,
Marco

**Comment by mdesalvo** [comment]
Hi @constnick,
I added two new methods in the Data object to fulfill the new use case:

- **DeclareNegativeIndividualType**: to **explicitly** state that the given individual **is not** of the given class
```csharp
OWLOntology ontology = new OWLOntology("ex:ont");
ontology.Model.ClassModel.DeclareClass(new RDFResource("ex:Cls"));
ontology.Data.DeclareIndividual(new RDFResource("ex:Idv"));
ontology.Data.DeclareNegativeIndividualType(ontology.Model, new RDFResource("ex:Idv"), new RDFResource("ex:Cls"));
```

- **CheckIsNegativeIndividualOf**: to check if the given individual is **explicitly not** of the given class (which was your original question)
```csharp
bool isIdvOfCls = ontology.Data.CheckIsNegativeIndividualOf(ontology.Model, new RDFResource("ex:Idv"), new RDFResource("ex:Cls"))
```

If this is desired, I'll release a new version with the code in the next few days.

Regards,
Marco

**Comment by constnick** [comment]
Yes, I think that's what is needed, thanks!
