### ISSUE TITLE
typo in the user guide

### ISSUE THREAD

**Issue by xloggr** [mdesalvo/OWLSharp#29]
I was looking through this [document](https://github.com/mdesalvo/OWLSharp/releases/download/v3.11.0/OWLSharp-3.11.0.pdf) and noticed a recurring typo, e.g.:

> EquivalentClass
> States that the given classes can be
> **threatened** the same by a reasoner,
> meaning that they are aliases
> 

I guess it was meant to be **treated**, not **threatened**

This typo also occurs in a few sections below (DisjojntClass, AllDisjointClasses, etc)

A similar typo is in the code sample:
`//**threat** this as a validation error`

was meant to be 
`//**treat** this as a validation error`

**Comment by mdesalvo** [comment]
Hi Dmitry,
thanks for the report, I'll update docs as soon as possible.

Regards,
Marco

**Comment by mdesalvo** [comment]
Updated docs uploaded.
